package models

type Tbl_tfr_his_trn_log struct {
	TRANS_DT                  string `gorm:"column:TRANS_DT"` //交易日期
	TRANS_MT                  string `gorm:"column:TRANS_MT"`	//交易时间
	SRC_QID                   string `gorm:"column:SRC_QID"`
	DES_QID                   string `gorm:"column:DES_QID"`
	MA_TRANS_CD               string `gorm:"column:MA_TRANS_CD"` //
	MA_TRANS_NM               string `gorm:"column:MA_TRANS_NM"`
	KEY_RSP                   string `gorm:"column:KEY_RSP"`
	KEY_REVSAL                string `gorm:"column:KEY_REVSAL"`
	KEY_CANCEL                string `gorm:"column:KEY_CANCEL"`
	RESP_CD                   string `gorm:"column:RESP_CD"`
	TRANS_ST                  string `gorm:"column:TRANS_ST"`
	MA_TRANS_SEQ              string `gorm:"column:MA_TRANS_SEQ"`
	ORIG_MA_TRANS_SEQ         string `gorm:"column:ORIG_MA_TRANS_SEQ"`
	ORIG_TRANS_SEQ            string `gorm:"column:ORIG_TRANS_SEQ"`
	ORIG_TERM_SEQ             string `gorm:"column:ORIG_TERM_SEQ"`
	ORIG_TRANS_DT             string `gorm:"column:ORIG_TRANS_DT"`
	MA_SETTLE_DT              string `gorm:"column:MA_SETTLE_DT"`
	ACCESS_MD                 string `gorm:"column:ACCESS_MD"`
	MSG_TP                    string `gorm:"column:MSG_TP"`
	PRI_ACCT_NO               string `gorm:"column:PRI_ACCT_NO"`
	ACCT_TP                   string `gorm:"column:ACCT_TP"`
	TRANS_PROC_CD             string `gorm:"column:TRANS_PROC_CD"`
	TRANS_AT                  string `gorm:"column:TRANS_AT"`
	TRANS_TD_TM               string `gorm:"column:TRANS_TD_TM"`
	TERM_SEQ                  string `gorm:"column:TERM_SEQ"`
	ACPT_TRANS_TM             string `gorm:"column:ACPT_TRANS_TM"`
	ACPT_TRANS_DT             string `gorm:"column:ACPT_TRANS_DT"`
	MCHNT_TP                  string `gorm:"column:MCHNT_TP"`
	POS_ENTRY_MD_CD           string `gorm:"column:POS_ENTRY_MD_CD"`
	POS_COND_CD               string `gorm:"column:POS_COND_CD"`
	ACPT_INS_ID_CD            string `gorm:"column:ACPT_INS_ID_CD"`
	FWD_INS_ID_CD             string `gorm:"column:FWD_INS_ID_CD"`
	TERM_ID                   string `gorm:"column:TERM_ID"`
	MCHNT_CD                  string `gorm:"column:MCHNT_CD"`
	CARD_ACCPTR_NM            string `gorm:"column:CARD_ACCPTR_NM"`
	RETRI_REF_NO              string `gorm:"column:RETRI_REF_NO"`
	REQ_AUTH_ID               string `gorm:"column:REQ_AUTH_ID"`
	TRANS_SUBCATA             string `gorm:"column:TRANS_SUBCATA"`
	INDUSTRY_ADDN_INF         string `gorm:"column:INDUSTRY_ADDN_INF"`//产品平台订单号
	TRANS_CURR_CD             string `gorm:"column:TRANS_CURR_CD"`
	SEC_CTRL_INF              string `gorm:"column:SEC_CTRL_INF"`
	IC_DATA                   string `gorm:"column:IC_DATA"`
	UDF_FLD_PURE              string `gorm:"column:UDF_FLD_PURE"`
	CERTIF_ID                 string `gorm:"column:CERTIF_ID"`
	NETWORK_MGMT_INF_CD       string `gorm:"column:NETWORK_MGMT_INF_CD"`
	ORIG_DATA_ELEMNT          string `gorm:"column:ORIG_DATA_ELEMNT"`
	RCV_INS_ID_CD             string `gorm:"column:RCV_INS_ID_CD"`
	TFR_IN_ACCT_NO_PURE       string `gorm:"column:TFR_IN_ACCT_NO_PURE"`
	TFR_IN_ACCT_TP            string `gorm:"column:TFR_IN_ACCT_TP"`
	TFR_OUT_ACCT_NO_PURE      string `gorm:"column:TFR_OUT_ACCT_NO_PURE"`
	ACPT_INS_RESV_PURE        string `gorm:"column:ACPT_INS_RESV_PURE"`
	TRR_OUT_ACCT_TP           string `gorm:"column:TRR_OUT_ACCT_TP"`
	ISS_INS_ID_CD             string `gorm:"column:ISS_INS_ID_CD"`
	CARD_ATTR                 string `gorm:"column:CARD_ATTR"`
	CARD_CLASS                string `gorm:"column:CARD_CLASS"`
	CARD_MEDIA                string `gorm:"column:CARD_MEDIA"`
	CARD_BIN                  string `gorm:"column:CARD_BIN"`
	CARD_BRAND                string `gorm:"column:CARD_BRAND"`
	ROUT_INS_ID_CD            string `gorm:"column:ROUT_INS_ID_CD"`
	ACPT_REGION_CD            string `gorm:"column:ACPT_REGION_CD"`
	BUSS_REGION_CD            string `gorm:"column:BUSS_REGION_CD"`
	USR_NO_TP                 string `gorm:"column:USR_NO_TP"`
	USR_NO_REGION_CD          string `gorm:"column:USR_NO_REGION_CD"`
	USR_NO_REGION_ADDN_CD     string `gorm:"column:USR_NO_REGION_ADDN_CD"`
	USR_NO                    string `gorm:"column:USR_NO"`
	SP_INS_ID_CD              string `gorm:"column:SP_INS_ID_CD"`
	INDUSTRY_INS_ID_CD        string `gorm:"column:INDUSTRY_INS_ID_CD"`
	ROUT_INDUSTRY_INS_ID_CD   string `gorm:"column:ROUT_INDUSTRY_INS_ID_CD"`
	INDUSTRY_MCHNT_CD         string `gorm:"column:INDUSTRY_MCHNT_CD"`
	INDUSTRY_TERM_CD          string `gorm:"column:INDUSTRY_TERM_CD"`
	INDUSTRY_MCHNT_TP         string `gorm:"column:INDUSTRY_MCHNT_TP"`
	ENTRUST_TP                string `gorm:"column:ENTRUST_TP"`
	PMT_MD                    string `gorm:"column:PMT_MD"`
	PMT_TP                    string `gorm:"column:PMT_TP"`
	PMT_NO                    string `gorm:"column:PMT_NO"`
	PMT_MCHNT_CD              string `gorm:"column:PMT_MCHNT_CD"`
	PMT_NO_INDUSTRY_INS_ID_CD string `gorm:"column:PMT_NO_INDUSTRY_INS_ID_CD"`
	PRI_ACCT_NO_CONV          string `gorm:"column:PRI_ACCT_NO_CONV"`
	TRANS_AT_CONV             string `gorm:"column:TRANS_AT_CONV"`
	TRANS_DT_TM_CONV          string `gorm:"column:TRANS_DT_TM_CONV"`
	TRANS_SEQ_CONV            string `gorm:"column:TRANS_SEQ_CONV"`
	MCHNT_TP_CONV             string `gorm:"column:MCHNT_TP_CONV"`
	RETRI_REF_NO_CONV         string `gorm:"column:RETRI_REF_NO_CONV"`//订单号的后12位
	ACPT_INS_ID_CD_CONV       string `gorm:"column:ACPT_INS_ID_CD_CONV"`
	TERM_ID_CONV              string `gorm:"column:TERM_ID_CONV"`
	MCHNT_CD_CONV             string `gorm:"column:MCHNT_CD_CONV"`
	MCHNT_NM_CONV             string `gorm:"column:MCHNT_NM_CONV"`
	UDF_FLD_PURE_CONV         string `gorm:"column:UDF_FLD_PURE_CONV"`
	SP_INS_ID_CD_CONV         string `gorm:"column:SP_INS_ID_CD_CONV"`
	EXPIRE_DT                 string `gorm:"column:EXPIRE_DT"`
	SETTLE_DT                 string `gorm:"column:SETTLE_DT"`
	TRANS_FEE                 string `gorm:"column:TRANS_FEE"`
	RESP_AUTH_ID              string `gorm:"column:RESP_AUTH_ID"`
	ACPT_RESP_CD              string `gorm:"column:ACPT_RESP_CD"`
	ADDN_RESP_DATA_PURE       string `gorm:"column:ADDN_RESP_DATA_PURE"`
	ADDN_AT_PURE              string `gorm:"column:ADDN_AT_PURE"`
	ISS_ADDN_DATA_PURE        string `gorm:"column:ISS_ADDN_DATA_PURE"`
	IC_RES_DAT_CUPS           string `gorm:"column:IC_RES_DAT_CUPS"`
	SW_RESV_PURE              string `gorm:"column:SW_RESV_PURE"`
	ISS_INS_RESV_PURE         string `gorm:"column:ISS_INS_RESV_PURE"`
	INDUSTRY_RESP_CD          string `gorm:"column:INDUSTRY_RESP_CD"`
	DEBT_AT                   string `gorm:"column:DEBT_AT"`
	DTL_INQ_DATA              string `gorm:"column:DTL_INQ_DATA"`
	TRANS_CHNL                string `gorm:"column:TRANS_CHNL"`
	INTERCH_MD_CD             string `gorm:"column:INTERCH_MD_CD"`
	TRANS_CHK_IN              string `gorm:"column:TRANS_CHK_IN"`
	MCHT_STLM_FLG             string `gorm:"column:MCHT_STLM_FLG"`
	INS_STLM_FLG              string `gorm:"column:INS_STLM_FLG"`
	MSG_RESV_FLD1             string `gorm:"column:MSG_RESV_FLD1"`
	MSG_RESV_FLD2             string `gorm:"column:MSG_RESV_FLD2"`
	MSG_RESV_FLD3             string `gorm:"column:MSG_RESV_FLD3"`
	TRANS_MTH                 string `gorm:"column:TRANS_MTH"`
	REC_UPD_TS                string `gorm:"column:REC_UPD_TS"`
	REC_CRT_TS                string `gorm:"column:REC_CRT_TS"`
	PROD_CD                   string `gorm:"column:PROD_CD"`
	TRAN_TP                   string `gorm:"column:TRAN_TP"`
	BIZ_CD                    string `gorm:"column:BIZ_CD"`
	REVEL_FLG                 string `gorm:"column:REVEL_FLG"`
	CANCEL_FLG                string `gorm:"column:CANCEL_FLG"`
	MSG_RESV_FLD4             string `gorm:"column:MSG_RESV_FLD4"`
	MSG_RESV_FLD5             string `gorm:"column:MSG_RESV_FLD5"`
	MSG_RESV_FLD6             string `gorm:"column:MSG_RESV_FLD6"`
	MSG_RESV_FLD7             string `gorm:"column:MSG_RESV_FLD7"`
	MSG_RESV_FLD8             string `gorm:"column:MSG_RESV_FLD8"`
	MSG_RESV_FLD9             string `gorm:"column:MSG_RESV_FLD9"`
}

func (t *Tbl_tfr_his_trn_log) TableName() string {
	return "tbl_tfr_his_trn_log"
}